In [6]:
import numpy as np
import pandas as pd

# Define activation functions
def tanh(x):
    return np.tanh(x)

def hard_tanh(x):
    return np.maximum(-1, np.minimum(1, x))

def softplus(x):
    return np.log1p(np.exp(x))

def relu(x):
    return np.maximum(0, x)

def leaky_relu(x, alpha=0.1):
    return np.where(x > 0, x, alpha * x)

# Input vector (3 features + bias)
x_raw = np.array([[0.5], [0.2], [0.1]])  # shape: (3,1)
x = np.vstack(([1.0], x_raw))           # shape: (4,1)

# Weights
W1 = np.array([
    [0.1, 0.1, 0.2, 0.3],
    [0.2, -0.3, 0.4, 0.1],
    [0.05, 0.2, -0.2, 0.1],
    [0.0, 0.3, -0.1, 0.2]
])  # shape: (4,4)

W2 = np.array([
    [0.2, 0.3, -0.1, 0.5, 0.1],
    [-0.2, 0.4, 0.3, -0.1, 0.2]
])  # shape: (2,5)

# Forward pass function
def forward_pass(x, W1, W2, activation_func):
    a1 = W1 @ x
    z1 = activation_func(a1)
    z1_aug = np.vstack(([1.0], z1))  # add bias
    y = W2 @ z1_aug
    return a1, z1, z1_aug, y

# Evaluate all activation functions
results = {}
activations = {
    "tanh": tanh,
    "hard_tanh": hard_tanh,
    "softplus": softplus,
    "relu": relu,
    "leaky_relu": leaky_relu
}

for name, func in activations.items():
    a1, z1, z1_aug, y = forward_pass(x, W1, W2, func)
    results[name] = {
        "a1": a1,
        "z1": z1,
        "z1_aug": z1_aug,
        "y": y
    }

# Compare hidden layer outputs
print("=== Hidden Layer Outputs (z1) for Each Activation Function ===\n")
df = pd.DataFrame({name: result["z1"].flatten() for name, result in results.items()}).T
df.columns = [f"Hidden Neuron {i+1}" for i in range(df.shape[1])]
print(df.round(4))  # Rounded for readability

# Print one full example (tanh) for manual checking
print("\n=== Example Forward Pass: tanh ===")
print("Input x (with bias):\n", x.T)
print("Hidden pre-activation a1:\n", results["tanh"]["a1"].T)
print("Hidden activation z1:\n", results["tanh"]["z1"].T)
print("Hidden layer with bias z1_aug:\n", results["tanh"]["z1_aug"].T)
print("Final output y:\n", results["tanh"]["y"].T)

# Print one full example (hard_tanh) for manual checking
print("\n=== Example Forward Pass: hard_tanh ===")
print("Input x (with bias):\n", x.T)
print("Hidden pre-activation a1:\n", results["hard_tanh"]["a1"].T)
print("Hidden activation z1:\n", results["hard_tanh"]["z1"].T)
print("Hidden layer with bias z1_aug:\n", results["hard_tanh"]["z1_aug"].T)
print("Final output y:\n", results["hard_tanh"]["y"].T)

# Print one full example (softplus) for manual checking
print("\n=== Example Forward Pass: softplus ===")
print("Input x (with bias):\n", x.T)
print("Hidden pre-activation a1:\n", results["softplus"]["a1"].T)
print("Hidden activation z1:\n", results["softplus"]["z1"].T)
print("Hidden layer with bias z1_aug:\n", results["softplus"]["z1_aug"].T)
print("Final output y:\n", results["softplus"]["y"].T)

# Print one full example (relu) for manual checking
print("\n=== Example Forward Pass: relu ===")
print("Input x (with bias):\n", x.T)
print("Hidden pre-activation a1:\n", results["relu"]["a1"].T)
print("Hidden activation z1:\n", results["relu"]["z1"].T)
print("Hidden layer with bias z1_aug:\n", results["relu"]["z1_aug"].T)
print("Final output y:\n", results["relu"]["y"].T)

# Print one full example (leaky_relu) for manual checking
print("\n=== Example Forward Pass: leaky_relu ===")
print("Input x (with bias):\n", x.T)
print("Hidden pre-activation a1:\n", results["leaky_relu"]["a1"].T)
print("Hidden activation z1:\n", results["leaky_relu"]["z1"].T)
print("Hidden layer with bias z1_aug:\n", results["leaky_relu"]["z1_aug"].T)
print("Final output y:\n", results["leaky_relu"]["y"].T)


=== Hidden Layer Outputs (z1) for Each Activation Function ===

            Hidden Neuron 1  Hidden Neuron 2  Hidden Neuron 3  Hidden Neuron 4
tanh                 0.2165           0.1391           0.1194           0.1489
hard_tanh            0.2200           0.1400           0.1200           0.1500
softplus             0.8092           0.7656           0.7549           0.7710
relu                 0.2200           0.1400           0.1200           0.1500
leaky_relu           0.2200           0.1400           0.1200           0.1500

=== Example Forward Pass: tanh ===
Input x (with bias):
 [[1.  0.5 0.2 0.1]]
Hidden pre-activation a1:
 [[0.22 0.14 0.12 0.15]]
Hidden activation z1:
 [[0.21651806 0.13909245 0.1194273  0.14888503]]
Hidden layer with bias z1_aug:
 [[1.         0.21651806 0.13909245 0.1194273  0.14888503]]
Final output y:
 [[ 0.32564833 -0.05383076]]

=== Example Forward Pass: hard_tanh ===
Input x (with bias):
 [[1.  0.5 0.2 0.1]]
Hidden pre-activation a1:
 [[0.22 0.14 0.12